# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'FishGame' do

pod 'lottie-ios'
pod 'STKitSwift'
pod 'STKitSwift/STSegmentedControl'
pod 'STKitSwift/STProgressView'
pod 'SwiftyJSON', '~> 4.0'
pod 'Toast-Swift', '~> 5.0.0'

  # Pods for FishGame

  target 'FishGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FishGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

