# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# Comment the next line if you don't want to use dynamic frameworks
use_frameworks!

target 'FishGame' do

pod 'lottie-ios'

  # Pods for FishGame

  target 'FishGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FishGameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

